spring:
  application:
    name: sb12_findex_team1

  datasource:
    url: jdbc:postgresql://localhost:5432/findex
    username: findex_user
    password: findex1234
    driver-class-name: org.postgresql.Driver

findex:
  auto-sync:
    cron: "0 0 0 * * *"   # 초 분 시 일 월 요일
    zone: "Asia/Seoul"