spring:
  application:
    name: sb12_findex_team1

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC
        open-in-view: false

public-data:
  index:
    base-url: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService
    stock-market-index-path: /getStockMarketIndex
    bond-market-index-path: /getBondMarketIndex
    derivation-product-market-index-path: /getDerivationProductMarketIndex
    service-key: ${PUBLIC_DATA_SERVICE_KEY}
    result-type: json

logging:
  level:
    root: info
    com.codeit.findex: info