spring:
  application:
    name: sb12_findex_team1

  datasource:
    url: jdbc:postgresql://localhost:5432/findex
    username: findex_user
    password: findex1234
    driver-class-name: org.postgresql.Driver

public-data:
  index:
    base-url: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService
    stock-market-index-path: /getStockMarketIndex
    bond-market-index-path: /getBondMarketIndex
    derivation-product-market-index-path: /getDerivationProductMarketIndex
    service-key: ${PUBLIC_DATA_SERVICE_KEY:}
    result-type: json

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace