DROP DATABASE IF EXISTS findex;

ALTER SCHEMA public OWNER TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE user1 IN SCHEMA public
	REVOKE ALL ON TABLES FROM findex_user;

ALTER DEFAULT PRIVILEGES FOR ROLE user1 IN SCHEMA public
	REVOKE ALL ON SEQUENCES FROM findex_user;

DROP USER IF EXISTS findex_user;

-- clean

CREATE USER findex_user WITH PASSWORD 'findex1234';

CREATE DATABASE findex OWNER findex_user;

GRANT ALL PRIVILEGES ON DATABASE findex TO findex_user;
